project:
  type: website
  render: 
    - "index.qmd"
    - "unidad_01.qmd"
    - "unidad_02.qmd"
    - "unidad_03.qmd"
    - "unidad_04.qmd"

website:
  title: "MNS"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: unidad_01.qmd
        text: Unidad 1
      - href: unidad_02.qmd
        text: Unidad 2
      - href: unidad_03.qmd
        text: Unidad 3
      - href: unidad_04.qmd
        text: Unidad 4

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



