project:
  type: website
  output-dir: docs
  render: 
    - "index.qmd"
    - "data-vis_00_intro.qmd"
    - "data-vis_01_r-graphics.qmd"
    - "data-vis_02_ggplot.qmd"
    - "data-vis_03_matplotlib.qmd"
    - "data-vis_04_seaborn.qmd"
    - "unidad_00.qmd"
    - "unidad_01.qmd"
    - "unidad_02.qmd"
    - "unidad_03.qmd"
    - "unidad_04.qmd"
    - "program_00_setup.qmd"
    - "program_01_loading-data.qmd"
    - "program_02_basics.qmd"
    - "program_03_tidy.qmd"
    - "program_04_eda.qmd"
    - "program_05_asociacion.qmd"

website:
  title: "Data Science Intro"
  search: false
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Programación"
        menu: 
          - text: "Setup"
            href: program_00_setup.qmd
          - text: "Lectura de datos"
            href: program_01_loading-data.qmd
          - text: "Hola R"
            href: program_02_basics.qmd
          - text: "Limpieza de datos"
            href: program_03_tidy.qmd
          - text: "Análisis exploratorio"
            href: program_04_eda.qmd
          - text: "Asociación"
            href: program_05_asociacion.qmd
      - text: "Data-vis"
        menu:
          - text: "Presentación"
            href: data-vis_00_intro.qmd
          - text: "R base"
            href: data-vis_01_r-graphics.qmd
          - text: "R ggplot"
            href: data-vis_02_ggplot.qmd
          - text: "Python matplotlib"
            href: data-vis_03_matplotlib.qmd
          - text: "Python seaborn"
            href: data-vis_04_seaborn.qmd
      - text: "Taller"
        menu:
          - text: "Presentación"
            href: unidad_00.qmd
          - text: "Unidad 1"
            href: unidad_01.qmd
          - text: "Unidad 2"
            href: unidad_02.qmd
          - text: "Unidad 3"
            href: unidad_03.qmd
          - text: "Unidad 4"
            href: unidad_04.qmd

format:
  html:
    theme: superhero
    css: styles.css
    toc: true



