---
title: "Data-vis"
subtitle: "Gráficos en R"
format: 
  html:
    toc: true
    toc-location: left
    toc-title: Contenido
    df-print: default
execute: 
  eval: true
  echo: true
  output: false
  warning: false
  error: false
---


# Paquete graphics

## ¿Qué es?

El paquete predeterminado para crear gráficos en R se llama "graphics". Este paquete viene preinstalado con las bibliotecas básicas de R y es conocido por su versatilidad en la producción de gráficos de alta calidad.

En R, "graphics" es un paquete integrado que proporciona una amplia gama de funciones y herramientas para crear diversos tipos de gráficos y diagramas. Se utiliza comúnmente para tareas básicas de visualización de datos, lo que lo convierte en una opción práctica para crear gráficos simples pero efectivos. Debido a que está incluido en la instalación estándar de R, no necesitas instalar paquetes adicionales para empezar a usarlo.

Aquí hay algunos puntos clave sobre el paquete "graphics" en R:

- **Paquete de Gráficos Predeterminado:** Cuando comienzas a trabajar con R, puedes utilizar el paquete "graphics" sin necesidad de instalaciones adicionales. Es la opción predeterminada para hacer gráficos básicos y representaciones gráficas.

- **Versatilidad:** El paquete "graphics" ofrece un conjunto versátil de funciones que te permiten crear una amplia variedad de gráficos, incluyendo gráficos de dispersión, gráficos de barras, histogramas y más. Puedes personalizar estos gráficos según tus necesidades específicas.

- **Gráficos de Buena Calidad:** Aunque "graphics" es un paquete gráfico básico, es capaz de producir gráficos de alta calidad para visualización y exploración de datos. Puede que no tenga todas las funciones avanzadas de paquetes especializados, pero cumple con muchas tareas comunes de trazado.

## Cómo funciona

El paquete "graphics" en R es una herramienta fundamental para crear una amplia variedad de gráficos y diagramas. Tiene una estructura bien definida que consiste en varias funciones que te permiten crear y personalizar gráficos. Aquí profundizaremos en la estructura del paquete "graphics" utilizando el texto proporcionado.



```{r}
#| eval: FALSE

# Functions for plotting

plot()
barplot()
boxplot()
hist()
contour()
assocplot()
pairs()
pie()
polygon()
persp()

# helpers

lines()
abline()

title()
legend()
text()


```


# Funciones para la Creación de Gráficos:

El núcleo del paquete "graphics" son sus funciones para la creación de gráficos. Estas funciones están diseñadas principalmente para trabajar con vectores, aunque también pueden manejar estructuras de datos. Estas funciones son los bloques de construcción para generar diferentes tipos de visualizaciones en R.

Trabajo con Vectores y Datos:

Las funciones dentro del paquete "graphics" están diseñadas principalmente para trabajar con vectores, que son estructuras de datos unidimensionales. Los vectores pueden representar datos numéricos o categóricos. Estas funciones pueden tomar vectores como entrada para crear una amplia gama de gráficos, como gráficos de dispersión, gráficos de líneas, histogramas y más.

Gráficos Personalizables:

Una de las características clave del paquete "graphics" es su capacidad para personalizar gráficos. Puedes controlar varios aspectos de las visualizaciones, incluidos colores, etiquetas, ejes, títulos y más. Este nivel de personalización te permite adaptar los gráficos a tus necesidades específicas.

Extensibilidad:

Si bien el paquete "graphics" ofrece una amplia gama de funciones de trazado, también es extensible. Esto significa que puedes construir visualizaciones más complejas combinando estas funciones básicas y agregando elementos adicionales a tus gráficos. Esta extensibilidad permite visualizaciones de datos creativas y sofisticadas.

## Tipos Comunes de Gráficos:

El paquete proporciona funciones para crear tipos comunes de gráficos, que incluyen:

- Gráficos de Dispersión: Visualización de la relación entre dos variables.
  
- Gráficos de Líneas: Representación de tendencias de datos a lo largo del tiempo u otra variable continua.
  
- Gráficos de Barras: Mostrar datos categóricos con barras.
  
- Histogramas: Visualización de la distribución de datos continuos.
  
- Diagramas de Caja: Ilustración de la distribución y variabilidad de los datos.
  
- Gráficos de Tarta: Representación de partes de un todo.

## Lecturas Adicionales

Lee [la documentación del paquete](https://stat.ethz.ch/R-manual/R-devel/library/graphics/html/00Index.html)

Visita [The R Graph Gallery](https://r-graph-gallery.com/) para ver una colección de figuras elaboradas con el paquete graphics.




